version: "3.8"

services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - 80:80
     # - 8080:8080 # Optional: Expose Traefik dashboard on port 8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  web:
    image: nfdi4chem/nmrkit:dev-latest
    pull_policy: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`dev.nmrkit.nmrxiv.org`)"
      - "traefik.http.routers.web.entrypoints=web"
      - "traefik.http.services.web.loadbalancer.server.port=80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/latest/registration/health"]
      interval: 1m
      timeout: 10s
      retries: 10
      start_period: 40s
    env_file:
      - ./.env

  prometheus:
    image: prom/prometheus
    container_name: nmrkit_prometheus
    ports:
      - 9090:9090
    volumes:
      - ./../prometheus_data/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana
    container_name: nmrkit_grafana
    ports:
      - 3000:3000
    volumes:
      - /mnt/data/grafana_data:/var/lib/grafana

  redis:
    image: "redis:alpine"
    ports:
        - "${FORWARD_REDIS_PORT:-6379}:6379"
    volumes:
        - "/mnt/data/redis:/data"
    networks:
        - default
    healthcheck:
        test: ["CMD", "redis-cli", "ping"]
        retries: 3
        timeout: 5s

  pgsql:
    image: "informaticsmatters/rdkit-cartridge-debian"
    ports:
      - "${FORWARD_DB_PORT:-5432}:5432"
    env_file:
      - ./.env
    volumes:
      - "/mnt/data/pgsql:/var/lib/postgresql/data"
    networks:
      - default
    healthcheck:
      test:
        [
            "CMD",
            "pg_isready",
            "-q",
            "-d",
            "${POSTGRES_DB}",
            "-U",
            "${POSTGRES_USER}",
        ]
      retries: 3
      timeout: 5s
  minio:
    image: 'minio/minio:latest'
    ports:
        - '${FORWARD_MINIO_PORT:-9001}:9001'
        - '${FORWARD_MINIO_CONSOLE_PORT:-8900}:8900'
    environment:
      - ./.env
    volumes:
        - /mnt/data/minio:/data/minio
    networks:
        - default
    command: minio server /data/minio --console-address ":8900"

volumes:
  prometheus_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /mnt/data/prometheus_data
  grafana_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /mnt/data/grafana_data
networks:
  default:
    name: nmrkit_vpc
